/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var proto_businessdata_pb = require('../proto/businessdata_pb.js');
goog.object.extend(proto, proto_businessdata_pb);
goog.exportSymbol('proto.data.GetProductPriceRequest', null, global);
goog.exportSymbol('proto.data.Product', null, global);
goog.exportSymbol('proto.data.ProductPrice', null, global);
goog.exportSymbol('proto.data.TaxRate', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.data.GetProductPriceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.data.GetProductPriceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.data.GetProductPriceRequest.displayName = 'proto.data.GetProductPriceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.data.Product = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.data.Product, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.data.Product.displayName = 'proto.data.Product';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.data.TaxRate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.data.TaxRate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.data.TaxRate.displayName = 'proto.data.TaxRate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.data.ProductPrice = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.data.ProductPrice, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.data.ProductPrice.displayName = 'proto.data.ProductPrice';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.data.GetProductPriceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.data.GetProductPriceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.data.GetProductPriceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.data.GetProductPriceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientrequest: (f = msg.getClientrequest()) && proto_businessdata_pb.ClientRequest.toObject(includeInstance, f),
    searchvalue: jspb.Message.getFieldWithDefault(msg, 2, ""),
    upc: jspb.Message.getFieldWithDefault(msg, 3, ""),
    value: jspb.Message.getFieldWithDefault(msg, 4, ""),
    name: jspb.Message.getFieldWithDefault(msg, 5, ""),
    pricelistuuid: jspb.Message.getFieldWithDefault(msg, 6, ""),
    businesspartneruuid: jspb.Message.getFieldWithDefault(msg, 7, ""),
    warehouseuuid: jspb.Message.getFieldWithDefault(msg, 8, ""),
    validfrom: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.data.GetProductPriceRequest}
 */
proto.data.GetProductPriceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.data.GetProductPriceRequest;
  return proto.data.GetProductPriceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.data.GetProductPriceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.data.GetProductPriceRequest}
 */
proto.data.GetProductPriceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto_businessdata_pb.ClientRequest;
      reader.readMessage(value,proto_businessdata_pb.ClientRequest.deserializeBinaryFromReader);
      msg.setClientrequest(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSearchvalue(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpc(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPricelistuuid(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setBusinesspartneruuid(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setWarehouseuuid(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setValidfrom(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.data.GetProductPriceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.data.GetProductPriceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.data.GetProductPriceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.data.GetProductPriceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientrequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto_businessdata_pb.ClientRequest.serializeBinaryToWriter
    );
  }
  f = message.getSearchvalue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUpc();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPricelistuuid();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getBusinesspartneruuid();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getWarehouseuuid();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getValidfrom();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
};


/**
 * optional ClientRequest clientRequest = 1;
 * @return {?proto.data.ClientRequest}
 */
proto.data.GetProductPriceRequest.prototype.getClientrequest = function() {
  return /** @type{?proto.data.ClientRequest} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.ClientRequest, 1));
};


/** @param {?proto.data.ClientRequest|undefined} value */
proto.data.GetProductPriceRequest.prototype.setClientrequest = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.GetProductPriceRequest.prototype.clearClientrequest = function() {
  this.setClientrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.GetProductPriceRequest.prototype.hasClientrequest = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string searchValue = 2;
 * @return {string}
 */
proto.data.GetProductPriceRequest.prototype.getSearchvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.data.GetProductPriceRequest.prototype.setSearchvalue = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string upc = 3;
 * @return {string}
 */
proto.data.GetProductPriceRequest.prototype.getUpc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.data.GetProductPriceRequest.prototype.setUpc = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string value = 4;
 * @return {string}
 */
proto.data.GetProductPriceRequest.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.data.GetProductPriceRequest.prototype.setValue = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string name = 5;
 * @return {string}
 */
proto.data.GetProductPriceRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.data.GetProductPriceRequest.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string priceListUuid = 6;
 * @return {string}
 */
proto.data.GetProductPriceRequest.prototype.getPricelistuuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.data.GetProductPriceRequest.prototype.setPricelistuuid = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string businessPartnerUuid = 7;
 * @return {string}
 */
proto.data.GetProductPriceRequest.prototype.getBusinesspartneruuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.data.GetProductPriceRequest.prototype.setBusinesspartneruuid = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string warehouseUuid = 8;
 * @return {string}
 */
proto.data.GetProductPriceRequest.prototype.getWarehouseuuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.data.GetProductPriceRequest.prototype.setWarehouseuuid = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional int64 validFrom = 9;
 * @return {number}
 */
proto.data.GetProductPriceRequest.prototype.getValidfrom = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.data.GetProductPriceRequest.prototype.setValidfrom = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.data.Product.prototype.toObject = function(opt_includeInstance) {
  return proto.data.Product.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.data.Product} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.data.Product.toObject = function(includeInstance, msg) {
  var f, obj = {
    uuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    id: jspb.Message.getFieldWithDefault(msg, 2, 0),
    value: jspb.Message.getFieldWithDefault(msg, 3, ""),
    name: jspb.Message.getFieldWithDefault(msg, 4, ""),
    help: jspb.Message.getFieldWithDefault(msg, 5, ""),
    documentnote: jspb.Message.getFieldWithDefault(msg, 6, ""),
    uomname: jspb.Message.getFieldWithDefault(msg, 7, ""),
    producttype: jspb.Message.getFieldWithDefault(msg, 8, ""),
    isstocked: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    isdropship: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    ispurchased: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    issold: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    imageurl: jspb.Message.getFieldWithDefault(msg, 13, ""),
    productcategoryname: jspb.Message.getFieldWithDefault(msg, 14, ""),
    productgroupname: jspb.Message.getFieldWithDefault(msg, 15, ""),
    productclassname: jspb.Message.getFieldWithDefault(msg, 16, ""),
    productclassificationname: jspb.Message.getFieldWithDefault(msg, 17, ""),
    weight: (f = msg.getWeight()) && proto_businessdata_pb.Decimal.toObject(includeInstance, f),
    volume: (f = msg.getVolume()) && proto_businessdata_pb.Decimal.toObject(includeInstance, f),
    upc: jspb.Message.getFieldWithDefault(msg, 20, ""),
    sku: jspb.Message.getFieldWithDefault(msg, 21, ""),
    shelfwidth: jspb.Message.getFieldWithDefault(msg, 22, 0),
    shelfheight: (f = msg.getShelfheight()) && proto_businessdata_pb.Decimal.toObject(includeInstance, f),
    shelfdepth: jspb.Message.getFieldWithDefault(msg, 24, 0),
    unitsperpack: jspb.Message.getFieldWithDefault(msg, 25, 0),
    unitsperpallet: (f = msg.getUnitsperpallet()) && proto_businessdata_pb.Decimal.toObject(includeInstance, f),
    guaranteedays: jspb.Message.getFieldWithDefault(msg, 27, 0),
    descriptionurl: jspb.Message.getFieldWithDefault(msg, 28, ""),
    versionno: jspb.Message.getFieldWithDefault(msg, 29, ""),
    taxcategory: jspb.Message.getFieldWithDefault(msg, 30, ""),
    description: jspb.Message.getFieldWithDefault(msg, 31, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.data.Product}
 */
proto.data.Product.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.data.Product;
  return proto.data.Product.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.data.Product} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.data.Product}
 */
proto.data.Product.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUuid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setHelp(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDocumentnote(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setUomname(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setProducttype(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsstocked(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsdropship(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIspurchased(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIssold(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageurl(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductcategoryname(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductgroupname(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductclassname(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductclassificationname(value);
      break;
    case 18:
      var value = new proto_businessdata_pb.Decimal;
      reader.readMessage(value,proto_businessdata_pb.Decimal.deserializeBinaryFromReader);
      msg.setWeight(value);
      break;
    case 19:
      var value = new proto_businessdata_pb.Decimal;
      reader.readMessage(value,proto_businessdata_pb.Decimal.deserializeBinaryFromReader);
      msg.setVolume(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpc(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setSku(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setShelfwidth(value);
      break;
    case 23:
      var value = new proto_businessdata_pb.Decimal;
      reader.readMessage(value,proto_businessdata_pb.Decimal.deserializeBinaryFromReader);
      msg.setShelfheight(value);
      break;
    case 24:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setShelfdepth(value);
      break;
    case 25:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUnitsperpack(value);
      break;
    case 26:
      var value = new proto_businessdata_pb.Decimal;
      reader.readMessage(value,proto_businessdata_pb.Decimal.deserializeBinaryFromReader);
      msg.setUnitsperpallet(value);
      break;
    case 27:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGuaranteedays(value);
      break;
    case 28:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescriptionurl(value);
      break;
    case 29:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersionno(value);
      break;
    case 30:
      var value = /** @type {string} */ (reader.readString());
      msg.setTaxcategory(value);
      break;
    case 31:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.data.Product.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.data.Product.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.data.Product} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.data.Product.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getHelp();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDocumentnote();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getUomname();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getProducttype();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getIsstocked();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getIsdropship();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getIspurchased();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getIssold();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getImageurl();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getProductcategoryname();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getProductgroupname();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getProductclassname();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getProductclassificationname();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getWeight();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      proto_businessdata_pb.Decimal.serializeBinaryToWriter
    );
  }
  f = message.getVolume();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      proto_businessdata_pb.Decimal.serializeBinaryToWriter
    );
  }
  f = message.getUpc();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getShelfwidth();
  if (f !== 0) {
    writer.writeInt32(
      22,
      f
    );
  }
  f = message.getShelfheight();
  if (f != null) {
    writer.writeMessage(
      23,
      f,
      proto_businessdata_pb.Decimal.serializeBinaryToWriter
    );
  }
  f = message.getShelfdepth();
  if (f !== 0) {
    writer.writeInt32(
      24,
      f
    );
  }
  f = message.getUnitsperpack();
  if (f !== 0) {
    writer.writeInt32(
      25,
      f
    );
  }
  f = message.getUnitsperpallet();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      proto_businessdata_pb.Decimal.serializeBinaryToWriter
    );
  }
  f = message.getGuaranteedays();
  if (f !== 0) {
    writer.writeInt32(
      27,
      f
    );
  }
  f = message.getDescriptionurl();
  if (f.length > 0) {
    writer.writeString(
      28,
      f
    );
  }
  f = message.getVersionno();
  if (f.length > 0) {
    writer.writeString(
      29,
      f
    );
  }
  f = message.getTaxcategory();
  if (f.length > 0) {
    writer.writeString(
      30,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      31,
      f
    );
  }
};


/**
 * optional string uuid = 1;
 * @return {string}
 */
proto.data.Product.prototype.getUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setUuid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 id = 2;
 * @return {number}
 */
proto.data.Product.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.data.Product.prototype.setId = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string value = 3;
 * @return {string}
 */
proto.data.Product.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setValue = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string name = 4;
 * @return {string}
 */
proto.data.Product.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string help = 5;
 * @return {string}
 */
proto.data.Product.prototype.getHelp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setHelp = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string documentNote = 6;
 * @return {string}
 */
proto.data.Product.prototype.getDocumentnote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setDocumentnote = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string uomName = 7;
 * @return {string}
 */
proto.data.Product.prototype.getUomname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setUomname = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string productType = 8;
 * @return {string}
 */
proto.data.Product.prototype.getProducttype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setProducttype = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional bool isStocked = 9;
 * @return {boolean}
 */
proto.data.Product.prototype.getIsstocked = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/** @param {boolean} value */
proto.data.Product.prototype.setIsstocked = function(value) {
  jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool isDropShip = 10;
 * @return {boolean}
 */
proto.data.Product.prototype.getIsdropship = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/** @param {boolean} value */
proto.data.Product.prototype.setIsdropship = function(value) {
  jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional bool isPurchased = 11;
 * @return {boolean}
 */
proto.data.Product.prototype.getIspurchased = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/** @param {boolean} value */
proto.data.Product.prototype.setIspurchased = function(value) {
  jspb.Message.setProto3BooleanField(this, 11, value);
};


/**
 * optional bool isSold = 12;
 * @return {boolean}
 */
proto.data.Product.prototype.getIssold = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/** @param {boolean} value */
proto.data.Product.prototype.setIssold = function(value) {
  jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional string imageURL = 13;
 * @return {string}
 */
proto.data.Product.prototype.getImageurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setImageurl = function(value) {
  jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string productCategoryName = 14;
 * @return {string}
 */
proto.data.Product.prototype.getProductcategoryname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setProductcategoryname = function(value) {
  jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string productGroupName = 15;
 * @return {string}
 */
proto.data.Product.prototype.getProductgroupname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setProductgroupname = function(value) {
  jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string productClassName = 16;
 * @return {string}
 */
proto.data.Product.prototype.getProductclassname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setProductclassname = function(value) {
  jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional string productClassificationName = 17;
 * @return {string}
 */
proto.data.Product.prototype.getProductclassificationname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setProductclassificationname = function(value) {
  jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional Decimal weight = 18;
 * @return {?proto.data.Decimal}
 */
proto.data.Product.prototype.getWeight = function() {
  return /** @type{?proto.data.Decimal} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Decimal, 18));
};


/** @param {?proto.data.Decimal|undefined} value */
proto.data.Product.prototype.setWeight = function(value) {
  jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.Product.prototype.clearWeight = function() {
  this.setWeight(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.Product.prototype.hasWeight = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional Decimal volume = 19;
 * @return {?proto.data.Decimal}
 */
proto.data.Product.prototype.getVolume = function() {
  return /** @type{?proto.data.Decimal} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Decimal, 19));
};


/** @param {?proto.data.Decimal|undefined} value */
proto.data.Product.prototype.setVolume = function(value) {
  jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.Product.prototype.clearVolume = function() {
  this.setVolume(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.Product.prototype.hasVolume = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional string upc = 20;
 * @return {string}
 */
proto.data.Product.prototype.getUpc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setUpc = function(value) {
  jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * optional string sku = 21;
 * @return {string}
 */
proto.data.Product.prototype.getSku = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setSku = function(value) {
  jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional int32 shelfWidth = 22;
 * @return {number}
 */
proto.data.Product.prototype.getShelfwidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/** @param {number} value */
proto.data.Product.prototype.setShelfwidth = function(value) {
  jspb.Message.setProto3IntField(this, 22, value);
};


/**
 * optional Decimal shelfHeight = 23;
 * @return {?proto.data.Decimal}
 */
proto.data.Product.prototype.getShelfheight = function() {
  return /** @type{?proto.data.Decimal} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Decimal, 23));
};


/** @param {?proto.data.Decimal|undefined} value */
proto.data.Product.prototype.setShelfheight = function(value) {
  jspb.Message.setWrapperField(this, 23, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.Product.prototype.clearShelfheight = function() {
  this.setShelfheight(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.Product.prototype.hasShelfheight = function() {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * optional int32 shelfDepth = 24;
 * @return {number}
 */
proto.data.Product.prototype.getShelfdepth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 24, 0));
};


/** @param {number} value */
proto.data.Product.prototype.setShelfdepth = function(value) {
  jspb.Message.setProto3IntField(this, 24, value);
};


/**
 * optional int32 unitsPerPack = 25;
 * @return {number}
 */
proto.data.Product.prototype.getUnitsperpack = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 25, 0));
};


/** @param {number} value */
proto.data.Product.prototype.setUnitsperpack = function(value) {
  jspb.Message.setProto3IntField(this, 25, value);
};


/**
 * optional Decimal unitsPerPallet = 26;
 * @return {?proto.data.Decimal}
 */
proto.data.Product.prototype.getUnitsperpallet = function() {
  return /** @type{?proto.data.Decimal} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Decimal, 26));
};


/** @param {?proto.data.Decimal|undefined} value */
proto.data.Product.prototype.setUnitsperpallet = function(value) {
  jspb.Message.setWrapperField(this, 26, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.Product.prototype.clearUnitsperpallet = function() {
  this.setUnitsperpallet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.Product.prototype.hasUnitsperpallet = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * optional int32 guaranteeDays = 27;
 * @return {number}
 */
proto.data.Product.prototype.getGuaranteedays = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 27, 0));
};


/** @param {number} value */
proto.data.Product.prototype.setGuaranteedays = function(value) {
  jspb.Message.setProto3IntField(this, 27, value);
};


/**
 * optional string descriptionURL = 28;
 * @return {string}
 */
proto.data.Product.prototype.getDescriptionurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 28, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setDescriptionurl = function(value) {
  jspb.Message.setProto3StringField(this, 28, value);
};


/**
 * optional string versionNo = 29;
 * @return {string}
 */
proto.data.Product.prototype.getVersionno = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 29, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setVersionno = function(value) {
  jspb.Message.setProto3StringField(this, 29, value);
};


/**
 * optional string taxCategory = 30;
 * @return {string}
 */
proto.data.Product.prototype.getTaxcategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 30, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setTaxcategory = function(value) {
  jspb.Message.setProto3StringField(this, 30, value);
};


/**
 * optional string description = 31;
 * @return {string}
 */
proto.data.Product.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 31, ""));
};


/** @param {string} value */
proto.data.Product.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 31, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.data.TaxRate.prototype.toObject = function(opt_includeInstance) {
  return proto.data.TaxRate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.data.TaxRate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.data.TaxRate.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    taxindicator: jspb.Message.getFieldWithDefault(msg, 3, ""),
    rate: (f = msg.getRate()) && proto_businessdata_pb.Decimal.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.data.TaxRate}
 */
proto.data.TaxRate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.data.TaxRate;
  return proto.data.TaxRate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.data.TaxRate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.data.TaxRate}
 */
proto.data.TaxRate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTaxindicator(value);
      break;
    case 4:
      var value = new proto_businessdata_pb.Decimal;
      reader.readMessage(value,proto_businessdata_pb.Decimal.deserializeBinaryFromReader);
      msg.setRate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.data.TaxRate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.data.TaxRate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.data.TaxRate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.data.TaxRate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTaxindicator();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRate();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto_businessdata_pb.Decimal.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.data.TaxRate.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.data.TaxRate.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.data.TaxRate.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.data.TaxRate.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string taxIndicator = 3;
 * @return {string}
 */
proto.data.TaxRate.prototype.getTaxindicator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.data.TaxRate.prototype.setTaxindicator = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Decimal rate = 4;
 * @return {?proto.data.Decimal}
 */
proto.data.TaxRate.prototype.getRate = function() {
  return /** @type{?proto.data.Decimal} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Decimal, 4));
};


/** @param {?proto.data.Decimal|undefined} value */
proto.data.TaxRate.prototype.setRate = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.TaxRate.prototype.clearRate = function() {
  this.setRate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.TaxRate.prototype.hasRate = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.data.ProductPrice.prototype.toObject = function(opt_includeInstance) {
  return proto.data.ProductPrice.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.data.ProductPrice} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.data.ProductPrice.toObject = function(includeInstance, msg) {
  var f, obj = {
    product: (f = msg.getProduct()) && proto.data.Product.toObject(includeInstance, f),
    pricelist: (f = msg.getPricelist()) && proto_businessdata_pb.Decimal.toObject(includeInstance, f),
    pricestd: (f = msg.getPricestd()) && proto_businessdata_pb.Decimal.toObject(includeInstance, f),
    pricelimit: (f = msg.getPricelimit()) && proto_businessdata_pb.Decimal.toObject(includeInstance, f),
    pricelistname: jspb.Message.getFieldWithDefault(msg, 5, ""),
    istaxincluded: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
    validfrom: jspb.Message.getFieldWithDefault(msg, 7, 0),
    currency: (f = msg.getCurrency()) && proto_businessdata_pb.Currency.toObject(includeInstance, f),
    taxrate: (f = msg.getTaxrate()) && proto.data.TaxRate.toObject(includeInstance, f),
    priceprecision: jspb.Message.getFieldWithDefault(msg, 10, 0),
    quantityonhand: (f = msg.getQuantityonhand()) && proto_businessdata_pb.Decimal.toObject(includeInstance, f),
    quantityreserved: (f = msg.getQuantityreserved()) && proto_businessdata_pb.Decimal.toObject(includeInstance, f),
    quantityordered: (f = msg.getQuantityordered()) && proto_businessdata_pb.Decimal.toObject(includeInstance, f),
    quantityavailable: (f = msg.getQuantityavailable()) && proto_businessdata_pb.Decimal.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.data.ProductPrice}
 */
proto.data.ProductPrice.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.data.ProductPrice;
  return proto.data.ProductPrice.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.data.ProductPrice} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.data.ProductPrice}
 */
proto.data.ProductPrice.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.data.Product;
      reader.readMessage(value,proto.data.Product.deserializeBinaryFromReader);
      msg.setProduct(value);
      break;
    case 2:
      var value = new proto_businessdata_pb.Decimal;
      reader.readMessage(value,proto_businessdata_pb.Decimal.deserializeBinaryFromReader);
      msg.setPricelist(value);
      break;
    case 3:
      var value = new proto_businessdata_pb.Decimal;
      reader.readMessage(value,proto_businessdata_pb.Decimal.deserializeBinaryFromReader);
      msg.setPricestd(value);
      break;
    case 4:
      var value = new proto_businessdata_pb.Decimal;
      reader.readMessage(value,proto_businessdata_pb.Decimal.deserializeBinaryFromReader);
      msg.setPricelimit(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPricelistname(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIstaxincluded(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setValidfrom(value);
      break;
    case 8:
      var value = new proto_businessdata_pb.Currency;
      reader.readMessage(value,proto_businessdata_pb.Currency.deserializeBinaryFromReader);
      msg.setCurrency(value);
      break;
    case 9:
      var value = new proto.data.TaxRate;
      reader.readMessage(value,proto.data.TaxRate.deserializeBinaryFromReader);
      msg.setTaxrate(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPriceprecision(value);
      break;
    case 11:
      var value = new proto_businessdata_pb.Decimal;
      reader.readMessage(value,proto_businessdata_pb.Decimal.deserializeBinaryFromReader);
      msg.setQuantityonhand(value);
      break;
    case 12:
      var value = new proto_businessdata_pb.Decimal;
      reader.readMessage(value,proto_businessdata_pb.Decimal.deserializeBinaryFromReader);
      msg.setQuantityreserved(value);
      break;
    case 13:
      var value = new proto_businessdata_pb.Decimal;
      reader.readMessage(value,proto_businessdata_pb.Decimal.deserializeBinaryFromReader);
      msg.setQuantityordered(value);
      break;
    case 14:
      var value = new proto_businessdata_pb.Decimal;
      reader.readMessage(value,proto_businessdata_pb.Decimal.deserializeBinaryFromReader);
      msg.setQuantityavailable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.data.ProductPrice.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.data.ProductPrice.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.data.ProductPrice} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.data.ProductPrice.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProduct();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.data.Product.serializeBinaryToWriter
    );
  }
  f = message.getPricelist();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_businessdata_pb.Decimal.serializeBinaryToWriter
    );
  }
  f = message.getPricestd();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto_businessdata_pb.Decimal.serializeBinaryToWriter
    );
  }
  f = message.getPricelimit();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto_businessdata_pb.Decimal.serializeBinaryToWriter
    );
  }
  f = message.getPricelistname();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getIstaxincluded();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getValidfrom();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getCurrency();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto_businessdata_pb.Currency.serializeBinaryToWriter
    );
  }
  f = message.getTaxrate();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.data.TaxRate.serializeBinaryToWriter
    );
  }
  f = message.getPriceprecision();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getQuantityonhand();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto_businessdata_pb.Decimal.serializeBinaryToWriter
    );
  }
  f = message.getQuantityreserved();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto_businessdata_pb.Decimal.serializeBinaryToWriter
    );
  }
  f = message.getQuantityordered();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      proto_businessdata_pb.Decimal.serializeBinaryToWriter
    );
  }
  f = message.getQuantityavailable();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      proto_businessdata_pb.Decimal.serializeBinaryToWriter
    );
  }
};


/**
 * optional Product product = 1;
 * @return {?proto.data.Product}
 */
proto.data.ProductPrice.prototype.getProduct = function() {
  return /** @type{?proto.data.Product} */ (
    jspb.Message.getWrapperField(this, proto.data.Product, 1));
};


/** @param {?proto.data.Product|undefined} value */
proto.data.ProductPrice.prototype.setProduct = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.ProductPrice.prototype.clearProduct = function() {
  this.setProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.ProductPrice.prototype.hasProduct = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Decimal priceList = 2;
 * @return {?proto.data.Decimal}
 */
proto.data.ProductPrice.prototype.getPricelist = function() {
  return /** @type{?proto.data.Decimal} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Decimal, 2));
};


/** @param {?proto.data.Decimal|undefined} value */
proto.data.ProductPrice.prototype.setPricelist = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.ProductPrice.prototype.clearPricelist = function() {
  this.setPricelist(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.ProductPrice.prototype.hasPricelist = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Decimal priceStd = 3;
 * @return {?proto.data.Decimal}
 */
proto.data.ProductPrice.prototype.getPricestd = function() {
  return /** @type{?proto.data.Decimal} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Decimal, 3));
};


/** @param {?proto.data.Decimal|undefined} value */
proto.data.ProductPrice.prototype.setPricestd = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.ProductPrice.prototype.clearPricestd = function() {
  this.setPricestd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.ProductPrice.prototype.hasPricestd = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Decimal priceLimit = 4;
 * @return {?proto.data.Decimal}
 */
proto.data.ProductPrice.prototype.getPricelimit = function() {
  return /** @type{?proto.data.Decimal} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Decimal, 4));
};


/** @param {?proto.data.Decimal|undefined} value */
proto.data.ProductPrice.prototype.setPricelimit = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.ProductPrice.prototype.clearPricelimit = function() {
  this.setPricelimit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.ProductPrice.prototype.hasPricelimit = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string priceListName = 5;
 * @return {string}
 */
proto.data.ProductPrice.prototype.getPricelistname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.data.ProductPrice.prototype.setPricelistname = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bool isTaxIncluded = 6;
 * @return {boolean}
 */
proto.data.ProductPrice.prototype.getIstaxincluded = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.data.ProductPrice.prototype.setIstaxincluded = function(value) {
  jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional int64 validFrom = 7;
 * @return {number}
 */
proto.data.ProductPrice.prototype.getValidfrom = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.data.ProductPrice.prototype.setValidfrom = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional Currency currency = 8;
 * @return {?proto.data.Currency}
 */
proto.data.ProductPrice.prototype.getCurrency = function() {
  return /** @type{?proto.data.Currency} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Currency, 8));
};


/** @param {?proto.data.Currency|undefined} value */
proto.data.ProductPrice.prototype.setCurrency = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.ProductPrice.prototype.clearCurrency = function() {
  this.setCurrency(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.ProductPrice.prototype.hasCurrency = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional TaxRate taxRate = 9;
 * @return {?proto.data.TaxRate}
 */
proto.data.ProductPrice.prototype.getTaxrate = function() {
  return /** @type{?proto.data.TaxRate} */ (
    jspb.Message.getWrapperField(this, proto.data.TaxRate, 9));
};


/** @param {?proto.data.TaxRate|undefined} value */
proto.data.ProductPrice.prototype.setTaxrate = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.ProductPrice.prototype.clearTaxrate = function() {
  this.setTaxrate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.ProductPrice.prototype.hasTaxrate = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional int32 pricePrecision = 10;
 * @return {number}
 */
proto.data.ProductPrice.prototype.getPriceprecision = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.data.ProductPrice.prototype.setPriceprecision = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional Decimal quantityOnHand = 11;
 * @return {?proto.data.Decimal}
 */
proto.data.ProductPrice.prototype.getQuantityonhand = function() {
  return /** @type{?proto.data.Decimal} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Decimal, 11));
};


/** @param {?proto.data.Decimal|undefined} value */
proto.data.ProductPrice.prototype.setQuantityonhand = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.ProductPrice.prototype.clearQuantityonhand = function() {
  this.setQuantityonhand(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.ProductPrice.prototype.hasQuantityonhand = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional Decimal quantityReserved = 12;
 * @return {?proto.data.Decimal}
 */
proto.data.ProductPrice.prototype.getQuantityreserved = function() {
  return /** @type{?proto.data.Decimal} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Decimal, 12));
};


/** @param {?proto.data.Decimal|undefined} value */
proto.data.ProductPrice.prototype.setQuantityreserved = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.ProductPrice.prototype.clearQuantityreserved = function() {
  this.setQuantityreserved(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.ProductPrice.prototype.hasQuantityreserved = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional Decimal quantityOrdered = 13;
 * @return {?proto.data.Decimal}
 */
proto.data.ProductPrice.prototype.getQuantityordered = function() {
  return /** @type{?proto.data.Decimal} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Decimal, 13));
};


/** @param {?proto.data.Decimal|undefined} value */
proto.data.ProductPrice.prototype.setQuantityordered = function(value) {
  jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.ProductPrice.prototype.clearQuantityordered = function() {
  this.setQuantityordered(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.ProductPrice.prototype.hasQuantityordered = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional Decimal quantityAvailable = 14;
 * @return {?proto.data.Decimal}
 */
proto.data.ProductPrice.prototype.getQuantityavailable = function() {
  return /** @type{?proto.data.Decimal} */ (
    jspb.Message.getWrapperField(this, proto_businessdata_pb.Decimal, 14));
};


/** @param {?proto.data.Decimal|undefined} value */
proto.data.ProductPrice.prototype.setQuantityavailable = function(value) {
  jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.data.ProductPrice.prototype.clearQuantityavailable = function() {
  this.setQuantityavailable(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.data.ProductPrice.prototype.hasQuantityavailable = function() {
  return jspb.Message.getField(this, 14) != null;
};


goog.object.extend(exports, proto.data);
